name: CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            qt_arch: 'linux_gcc_64' 
            artifact_name: EZImageManipulator-Linux.zip
          - os: windows-latest
            qt_arch: 'win64_msvc2022_64' 
            artifact_name: EZImageManipulator-Windows.zip
    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.2'
        target: 'desktop'
        arch: ${{ matrix.qt_arch }}
        
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.0'

    - name: Configure and Build on Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="%QT_ROOT_DIR%"
        cmake --build build --config Release

    - name: Configure and Build on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_PREFIX_PATH="${{ env.QT_ROOT_DIR }}"
        cmake --build build --config Release

    - name: Package Executable
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          windeployqt --release build/Release/EZImageManipulator.exe
          7z a EZImageManipulator-Windows.zip ./build/Release/*
          echo "EXECUTABLE_PATH=EZImageManipulator-Windows.zip" >> $GITHUB_ENV
        else
          (cd build && zip -r ../EZImageManipulator-Linux.zip .)
          echo "EXECUTABLE_PATH=EZImageManipulator-Linux.zip" >> $GITHUB_ENV
        fi
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Executable-${{ matrix.os }}
        path: ${{ env.EXECUTABLE_PATH }}

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.EXECUTABLE_PATH }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "v1.0.0-${{ github.run_number }}"
        name: "Release ${{ github.run_number }}"
        body: "Automated build release."
        allowUpdates: true
