name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            qt_arch: 'linux_gcc_64' 
            artifact_name: EZImageManipulator-Linux.zip
          - os: windows-latest
            qt_arch: 'win64_msvc2022_64' 
            artifact_name: EZImageManipulator-Windows.zip

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.2'
        target: 'desktop'
        arch: ${{ matrix.qt_arch }}
        
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.0'

    - name: Configure CMake
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${{ env.QT_ROOT_DIR }}"
        else
          cmake -S . -B build -G "Ninja" -DCMAKE_PREFIX_PATH="${{ env.QT_ROOT_DIR }}"
        fi
      shell: bash

    - name: Build Project
      run: cmake --build build --target EZImageManipulator

    - name: Package Executable
      shell: bash
      run: |
        BUILD_DIR=build
        
        if [ "${{ runner.os }}" == "Windows" ]; then
          windeployqt --release $BUILD_DIR/Release/EZImageManipulator.exe
          7z a EZImageManipulator-Windows.zip ./$BUILD_DIR/Release/
          echo "EXECUTABLE_PATH=EZImageManipulator-Windows.zip" >> $GITHUB_ENV
        else
          zip -r EZImageManipulator-Linux.zip ./$BUILD_DIR/
          echo "EXECUTABLE_PATH=EZImageManipulator-Linux.zip" >> $GITHUB_ENV
        fi
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Executable-${{ matrix.os }}
        path: ${{ env.EXECUTABLE_PATH }}

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.EXECUTABLE_PATH }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "v1.0.0-${{ github.run_number }}"
        name: "Release ${{ github.run_number }}"
        body: "Automated build release."
        allowUpdates: true
